name: CD - Deploy to Cloud Run

on:
  push:
    branches: [ "main" ] # Only trigger when code is merged into main
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  SERVICE_NAME: quantum-tetris
  REPOSITORY_NAME: game-images
  IMAGE_NAME: quantum-tetris

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker for Google Artifact Registry
        run: 'gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build and Push Docker Image
        run: |-
          docker build --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" .
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE_NAME }}'
          region: '${{ env.GAR_LOCATION }}'
          image: '${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          flags: '--allow-unauthenticated'

      - name: Show Deployed URL
        run: echo "The game is deployed at ${{ steps.deploy.outputs.url }}"