name: CI - Validate Web Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  validate-web-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Linting Tools
        run: npm install -g htmlhint jshint

      - name: Lint HTML
        run: htmlhint .

      - name: Lint JavaScript
        run: jshint .