name: Build, Test, and Deploy Quantum-Tetris

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks out your repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Logs into Docker Hub using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Sets up Docker Buildx for building
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Builds the image from your Dockerfile and pushes it to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quantum-tetris:latest

      # Step 5: If the push is to the 'main' branch, it triggers the deployment on Render
      - name: Trigger Render Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"